[build-system]
requires = ["setuptools>=69"]
build-backend = "setuptools.build_meta"

[project]
name = "libreria-parcial-sebas"
version = "0.1.0"
description = "Modulo de calculo de precio final para una libreria."
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
addopts = "-ra --cov=src/libreria --cov-report=term-missing"

